### ISSUE TITLE
Dose not Disable the VR mod Completly

### ISSUE THREAD

**Issue by GrubPL** [Juliasmatius/Portal-2-VR-manager#1]
So basicly the Remove Thing just dosent disable it fully, like it disables vr, tho the offset of the gun is still pulling from other files that werent  edited, ya might want to just create or make the user create on the setup an "Unused" or "Disabled" folder those other files would be moved to, or it might have something with me having the dlc folder with an 6 instead of the default 3 but i have more mods than the vr mod so i had to. best regards 

-Grub

**Comment by Juliasmatius** [comment]
Fixed!
